// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADrwgDK4WpVgOYySbxgPg2mbxWeVUk70c',
    appId: '1:429439467228:web:48708cdc5e730d8e0d7e19',
    messagingSenderId: '429439467228',
    projectId: 'smart-expense-tracker-d9c4c',
    authDomain: 'smart-expense-tracker-d9c4c.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-d9c4c.firebasestorage.app',
    measurementId: 'G-HWEV19R859',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPuOkIeruJVE0f5-taHdM3xoGJmqTXdQQ',
    appId: '1:429439467228:android:8cdce92597dccfc90d7e19',
    messagingSenderId: '429439467228',
    projectId: 'smart-expense-tracker-d9c4c',
    storageBucket: 'smart-expense-tracker-d9c4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi7xqjnmROfcmX7gPMoLGz-8OxnbUnJD8',
    appId: '1:429439467228:ios:25880a667f53b0ef0d7e19',
    messagingSenderId: '429439467228',
    projectId: 'smart-expense-tracker-d9c4c',
    storageBucket: 'smart-expense-tracker-d9c4c.firebasestorage.app',
    iosBundleId: 'com.smart.expensetracker',
  );
}
